name: BukkitUtil
main: me.fox476.mainutil.MainUtil
version: 1.0
commands:
   Blank:
      description: Blank description.
      usage: /<command>
permissions:
   keepinv.enable: 
      description: Keep inv.
      default: false